### ISSUE TITLE
[GENERAL] Add possibility to convert new-line-terminated textual files into the dlt format

### ISSUE THREAD

**Issue by svlad-90** [svlad-90/DLT-Message-Analyzer#156]
As a user, I want to be able to use dlt-viewer not only for automotive-related projects:
- many other projects do not have the possibility to deploy the whole dlt infrastructure on their targets 
- others are running on the OS-s, which are not officially supported by the dlt-daemon ( e.g. windows )

Still, the dlt-viewer + DLT-Message-Analyzer provide such a good experience, that I wish to wider the range of the projects, for which it can be used.

For this purpose, I want to have the possibility to convert any textual "new line separated" file into the dlt format in order to use the benefits of the dlt-viewer's & DLT_Message-Analyzer's features. That will allow to wider the range of the users a lot.

**Comment by artemkomyshan** [comment]
Hi,
Interesting functionality, how can I convert any textual "new line separated" file into the dlt file now?

**Comment by svlad-90** [comment]
Hi @artemkomyshan, search for the "convert-txt-to-dlt-file" command on this page for more details: https://github.com/svlad-90/DLT-Message-Analyzer/blob/master/md/debug_console/debug_console.md

It gets sourceFile & targetFile parameters and does the thing.

Note! As I've needed that functionality quite fast, I've done processing right in the UI thread. Thus, dlt-viewer might hang for a  while till the conversion is ongoing. ))
