### ISSUE TITLE
Error message was displayed when executing dlt-viewer

### ISSUE THREAD

**Issue by HappyRia** [svlad-90/DLT-Message-Analyzer#202]
**Describe the bug**
Error message was displayed when executing dlt-viewer

**Screenshots**
![image](https://github.com/svlad-90/DLT-Message-Analyzer/assets/154211279/8a1b099b-68d7-4b0f-a488-610b7ac6ccee)

**Env**
[dlt-viewer] v2.25.0
Windows

![image](https://github.com/svlad-90/DLT-Message-Analyzer/assets/154211279/d7994170-9f3f-4946-b81e-7276b47852ef)

[DLT-Message-Analyzer] v.1.0.27

**Comment by HappyRia** [comment]
After building the DLT-Message-Analyzer plugin and launching dlt-viewer, an error occurred. The error message is garbled and I don't know what the cause of the error is. Can anyone tell me what the possible causes are?

**Comment by HappyRia** [comment]
When I checked the error message in the Qt Creator debugger, I found out what the garbled characters were.

-------------The plugin D:/build/bin/plugins/DLT-Message-Analyzer.dllcannot be loaded. Error: Cannot load library D:\build\bin\plugins\DLT-Message-Analyzer.dll: **Specified module not found.**

**Comment by svlad-90** [comment]
Hi @HappyRia, first of all, thank you for creating this issue!

Also, I am sorry for the delay in getting back to you. I'm on vacation right now. Due to this, I check my email box sparingly. ))

Please, give me some time. I'll set up a development environment on my Windows OS and will try to reproduce your issue.

As I understand, you have it with the following environment:

OS: Windows
dlt-viewer: v2.25.0
DLT-Message-Analyzer: v.1.0.27
Qt version: 6.x.y

**=> Could you please clarify whether you ran the dlt-viewer from the build folder or tried to install it ( build the install CMake target ) and run it from the installation folder?**

**Comment by HappyRia** [comment]
Hi @svlad-90,

Thanks for the reply and your help in debugging.

It's the latter, I used the build_sdk_windows_qt5_MSVC_cmake_interactive.bat in https://github.com/COVESA/dlt-viewer.

Would it be possible for you to also release the Windows version of dlt-message-analyzer.dll that is compatible with dlt-viewer v2.25.0?

**Comment by HappyRia** [comment]
Hi @svlad-90,

Thanks for taking your time during the vacation. That would be very helpful for me. I hope you would come up with a solution soon. Please keep me updated.

**Comment by svlad-90** [comment]
Hi @HappyRia, I've prepared the following fix:
https://github.com/svlad-90/DLT-Message-Analyzer/pull/205

Please verify whether it is functional for you. I've checked it on Windows OS and will also check it on Ubuntu. But I'll merge the fix only after your confirmation.

**Comment by HappyRia** [comment]
Hi @svlad-90,

Thanks, but I got an error during build step as follow.

-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning at scripts/windows/version.cmake:12 (find_package):
  By not providing "FindQt6.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt6", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt6" (requested
  version 6) with any of the following names:

    Qt6Config.cmake
    qt6-config.cmake

  Add the installation prefix of "Qt6" to CMAKE_PREFIX_PATH or set "Qt6_DIR"
  to a directory containing one of the above files.  If "Qt6" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:19 (include)


CMake Error at scripts/windows/version.cmake:21 (find_package):
  By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5" (requested
  version 5) with any of the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:19 (include)


-- Configuring incomplete, errors occurred!
####################################
###       ERROR occured          ###
####################################
